name: Paula Cunniffe
favicon: null
layout_spectrum: 0.8622393640689552
typography_spectrum: 0.01874709501862526
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07962670247070491
  lightness: 0.5602823877707124
  saturation: 0.729972438653931
  rhythmicContrast: 0.4268654810730368
purpose: []
