name: Paula Cunniffe
favicon: null
layout_spectrum: 0.14163
typography_spectrum: 0.38483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e1d8c7'
    - '#c0b4a4'
    - '#efebdf'
    - '#9f9989'
  brandStrength: 0.07962670247070491
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
