name: In Between Mountains
favicon: null
layout_spectrum: 0.49518
typography_spectrum: 0.38483
title: In Between Mountains
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#304d53'
    - '#fee0a4'
    - '#f4400b'
    - '#f99826'
    - '#8ba5a6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
